[project]
name = "nikolai-ml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "pelkoa-glitch", email = "sergey.koroteev.dev@gmail.com" }
]
requires-python = ">=3.12"
dependencies = ["g2p-en (>=2.1.0,<3.0.0)", "numpy (==1.26.4)", "scipy (==1.11.4)", "nltk (>=3.10.3,<4.0.0)"]

[project.scripts]
nikolai-ml = "nikolai_ml:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
